services:
  redis:
    image: redis:7-alpine
    container_name: data-ie-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - data-ie-network

  upload-api:
    build:
      context: .
      dockerfile: apps/upload-api/Dockerfile
    container_name: data-ie-upload-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - data-ie-network
    restart: unless-stopped

  processor-service:
    build:
      context: .
      dockerfile: apps/processor-service/Dockerfile
    container_name: data-ie-processor-service
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - data-ie-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  data-ie-network:
    driver: bridge
